### ISSUE TITLE
Configuration for  remote Calendar is not in FF profile (2.1.6.3)

### ISSUE THREAD

**Issue by dapgo** [neandr/reminderfox#3]
I am using some Firefox browsers (portables)  and I can configure an use reminderfox on them.

If I copy the folder to another computer, in the target computer Reminderfox loss the configuration for Remote calendars (and maybe more other parameters).

Where Reminderfox store its configuration? 
is not using the standard (the FF profile folder)?
Is using the windows registry?

**Comment by neandr** [comment]
Reminderfox stores it configuration in the file: profile.js which can be found in the current profile directory.
The reminders/todos are stored in *.ICS file which is normally part of the profile as well. And the configuration of the remote calendar(s) are stored in a separate file with the extension *.ICS.DAV
(eg: /media/guenter/DATA/_Mozilla/reminderfox.ics.dav) which is stored at the same place as it's .ICS file.
Please also note:
-- the pw for the remote calendars are store with the FX/TB password manager
-- the storage location of the reminderfox.ics file is stored in the prefs.js. So porting the profile etc to another location/device needs to adjust that.

**Comment by dapgo** [comment]
After some testing I can't make it work...
I edited prefs.js modifying the path change ( drive)

user_pref("extensions.reminderFox.storeICS", "{\"WINNT\":\"D:\\\\Portables\\\\Waterfox_browsers\\\\Data\\\\profile\\\\reminderfox\\\\reminderfox.ics\"}");
with
user_pref("extensions.reminderFox.storeICS", "{\"WINNT\":\"C:\\\\Portables\\\\Waterfox_browsers\\\\Data\\\\profile\\\\reminderfox\\\\reminderfox.ics\"}");

After opening ReminderFox  in "Options:General:Default data location"  i can see the path at c: drive. 
but at Options:Sync:Remote calendar there is not configuration.

Also I tried to export/import configuration from Options:General:ReminderFox Data,  " Import/Export" button, :
rmFXprefs_20190516T164913Z.js (Success message but no remote calendar)

At  .\profile\reminderfox i have the reminderfox.ics.dav containing the server configuration but it seems that reminderfox is not looking there.

I have done tests with ff52 and 56
