### ISSUE TITLE
reminderfox configuration and paths

### ISSUE THREAD

**Issue by dapgo** [neandr/reminderfox#4]
After some testing I can't make it work...
I edited prefs.js modifying the path change ( drive)

user_pref("extensions.reminderFox.storeICS", "{\"WINNT\":\"D:\\\\Portables\\\\Waterfox_browsers\\\\Data\\\\profile\\\\reminderfox\\\\reminderfox.ics\"}");
with
user_pref("extensions.reminderFox.storeICS", "{\"WINNT\":\"C:\\\\Portables\\\\Waterfox_browsers\\\\Data\\\\profile\\\\reminderfox\\\\reminderfox.ics\"}");

After opening ReminderFox  in "Options:General:Default data location"  i can see the path at c: drive. 
but at Options:Sync:Remote calendar there is not configuration.

Also I tried to export/import configuration from Options:General:ReminderFox Data,  " Import/Export" button, :
rmFXprefs_20190516T164913Z.js (Success message but no remote calendar)

At  .\profile\reminderfox i have the reminderfox.ics.dav containing the server configuration but it seems that reminderfox is not looking there.

what about replacing absolute paths by ff relative ones? 
I have done tests with ff52 and 56

_Originally posted by @dapgo in https://github.com/neandr/reminderfox/issues/3#issuecomment-493156571_

**Comment by neandr** [comment]
Try the following steps:
1. from the old system export your reminderfox.ics and the  reminderfox.ics.dav files
2. also export the Reminderfox prefs using RmFX --> Options --> Import/Export. There on the popup you have the export button for the prefs. (Think you did it already with rmFXprefs_20190516T164913Z.js)

3. on the new system close FX/TB and do a WIN/OS file import of the three files to your current FX/TB directory (or any other known directory).
4. open FX/TB without opening Reminderfox. Open the FX/TB preference editor and search for extensions.reminderFox.storeICS and clear the value.
5. open Reminderfox --> Options and select the location of reminderfox.ics file

That should bring back your reminders/todos. Remember the PW are stored in the password manager, so for a new installation you need to setup them manually.
If you have the correct pw settings for the remote calendars you can resync and the reminders tied to a remote calendar should be back/updated.
