### ISSUE TITLE
Issue with 2.1.6.8 and WF Classic 202001 (56.3) or PM28

### ISSUE THREAD

**Issue by dapgo** [neandr/reminderfox#6]
After upgrading the addon to last version, in WF the list/calendar layout is not displayed.

![WF_Missing_List_cal_layout](https://user-images.githubusercontent.com/4981669/72546017-4dcacc80-388a-11ea-936c-9d3489853a76.png)
![events_exist](https://user-images.githubusercontent.com/4981669/72546053-5fac6f80-388a-11ea-9524-c397f2465bd9.png)

**Comment by dapgo** [comment]
same issue after upgrading the addon on a PM28
![rmfx_PM28](https://user-images.githubusercontent.com/4981669/72549441-00059280-3891-11ea-87bf-38fada52c560.png)

**Comment by neandr** [comment]
Sorry about your problem.
Please the notes with the 2.1.6.8 which states to be compatible with TB60 and WF56.
TB68 and WF2020 are using a different technology, not the legacy base.
So current release are ONLY usable with the tested environment.

**Comment by dapgo** [comment]
@neandr the test was done with Waterfox 56.3 aka Waterfox Classic,  you can see in the screenshot, window title.  Recently  Waterfox changed their versioning system,  being now WF Classic (56) or Current (68) both with version YYYYMM.
Do you think that the problem is due to reuse previous rmfx configuration?

**Comment by neandr** [comment]
Not sure what the problem is. Just tested with RmFX [downloaded  from here ](https://github.com/neandr/reminderfox/releases).
For me it installed as: 
> ReminderFox  [2.1.6.8]     20191123_1843
>   Profile directory: /home/guenter/.waterfox/08ra7tto.P1
>   Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0 Waterfox/56.3 (en-US)

Check this with Reminderfox About dialog, just open it and the installation string like above is build. With "Paste" (Cntrl V) you can add it to a reply msg

**Comment by dapgo** [comment]
here you have 
ReminderFox  [2.1.6.8]     20191123_1843
  Profile directory: C:\Daniel\00_PortableBrowsers\Waterfox_browsers\profile
  Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0 Waterfox/56.3 (en-US)

**Comment by neandr** [comment]
Did you checked the console? 
With WFX you can open it with Cntrl J. Check for RmFX specific. Select and copy&paste it to reply. Send it to gNeandr at web dot de

**Comment by dapgo** [comment]
Good idea, I forgot to check the console,.
Anyway I decided to do a clean install, so I uninstalled the addon, I deleted the folder at profile, all entries from prefs,.js (same than about:config) and then I installed  and voila (the layout is the expected)
![rmfx_clean_install_PM28](https://user-images.githubusercontent.com/4981669/72610401-88367700-3927-11ea-92d6-b9d403fe31b5.png)
Now ia m trying to figure what is different in pref.js

**Comment by dapgo** [comment]
I think cause of the issue is related to the folder reminderfox in profile.  After deleting the folder  I installed ReminderFox 2.1.6.8 on a Basilisk that previously had rmfx v2.1.6.3 and everything worked fine ; this time i haven't removed entries on prefs.js . In brief I can confirm you that RMFX is fully compatible with Basilisk/FF52 :)
