### ISSUE TITLE
Sync minor problem

### ISSUE THREAD

**Issue by dapgo** [neandr/reminderfox#7]
After installing v 2.1.6.8, i copy my configured "reminderfox.ics.dav" file in profile\reminderfox
Then I go to "sync remote calendars""[M] Mycal" and nothing happen
Then I go to Sync setup, Mycal, Configure, Login  
and I receive the message "Validated Remote Eventes (10)

So the rmfx can login on server and  see the entries, but entries are not downloaded to rmfx.
But if i create a new event, automatically all the events are downloaded/synced from the server.

**Comment by neandr** [comment]
That you don't get yr reminders downloaded as you "imported" the dav file is --> normal.
The sync is based on a stamp comparison between your local file and the remote system. If -- at the moment you "import" the dav file -- those stamps are equal (RmFx reads from remote and compares with the local) no download is triggered.
After you added a new reminder a deeper comparision is started, so the missing ICS data is downloaded.
